import {
  MCPConfig,
  MCPSSEServer,
  MCPSHTTPServer,
  MCPStdioServer,
  SettingsValue,
} from "#/types/settings";
import type {
  MCPAuthCredential,
  MCPAuthenticationConfig,
  MCPJsonValue,
  MCPOAuthState,
} from "#/types/mcp-auth";
import type { MCPServerConfig } from "#/types/mcp-server";
import { toMcpServerName } from "#/utils/mcp-server-name";

const EMPTY_MCP_CONFIG: MCPConfig = {
  sse_servers: [],
  stdio_servers: [],
  shttp_servers: [],
};

export const REDACTED_MCP_SECRET_VALUE = "**********";

type SdkMcpServerConfig = Record<string, SettingsValue | MCPAuthCredential>;
type SdkMcpConfig = Record<string, SdkMcpServerConfig>;

/**
 * The dict key for an SSE/SHTTP server doubles as its display name once a
 * user provides one. Keys that match the auto-generated fallback pattern
 * (``sse``, ``shttp``, ``shttp_1``, …) emitted by {@link toSdkMcpConfig}
 * carry no user intent, so we surface them as "no name" — re-serializing
 * regenerates the identical fallback key and existing configs are left
 * untouched.
 */
function userGivenServerName(
  serverName: string,
  base: "sse" | "shttp",
): string | undefined {
  const autoGenerated = new RegExp(`^${base}(_\\d+)?$`);
  return autoGenerated.test(serverName) ? undefined : serverName;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

export function getSdkMcpServerMap(
  value: unknown,
): Record<string, unknown> | null {
  if (!isRecord(value)) return null;

  const mcpServers = value.mcpServers;
  if (
    isRecord(mcpServers) &&
    !("url" in mcpServers) &&
    !("command" in mcpServers)
  ) {
    return mcpServers;
  }

  return value;
}

export function stringRecord(
  value: unknown,
): Record<string, string> | undefined {
  if (!isRecord(value)) return undefined;
  const entries = Object.entries(value).filter(
    (entry): entry is [string, string] => typeof entry[1] === "string",
  );
  return entries.length > 0 ? Object.fromEntries(entries) : undefined;
}

export function hasRedactedMcpSecretLeaf(value: unknown): boolean {
  if (value === REDACTED_MCP_SECRET_VALUE) return true;
  if (Array.isArray(value)) return value.some(hasRedactedMcpSecretLeaf);
  if (isRecord(value))
    return Object.values(value).some(hasRedactedMcpSecretLeaf);
  return false;
}

function getOAuthState(value: unknown): MCPOAuthState | undefined {
  if (!isRecord(value)) return undefined;
  const state: MCPOAuthState = {};
  if (isRecord(value.tokens)) {
    state.tokens = value.tokens as NonNullable<MCPOAuthState["tokens"]>;
  }
  if (isRecord(value.client_info)) {
    state.client_info = value.client_info as NonNullable<
      MCPOAuthState["client_info"]
    >;
  }
  if (
    typeof value.token_expires_at === "number" ||
    value.token_expires_at === null
  ) {
    state.token_expires_at = value.token_expires_at;
  }
  return Object.keys(state).length > 0 ? state : undefined;
}

function normalizeTaggedAuthCredential(
  value: unknown,
): MCPAuthCredential | undefined {
  if (!isRecord(value)) return undefined;
  switch (value.strategy) {
    case "none":
      return { strategy: "none" };
    case "api_key":
      if (typeof value.value !== "string") return undefined;
      return {
        strategy: "api_key",
        value: value.value,
        ...(typeof value.header_name === "string" && {
          header_name: value.header_name,
        }),
      };
    case "bearer":
      if (typeof value.value !== "string") return undefined;
      return { strategy: "bearer", value: value.value };
    case "basic":
      if (
        typeof value.username !== "string" ||
        typeof value.password !== "string"
      ) {
        return undefined;
      }
      return {
        strategy: "basic",
        username: value.username,
        password: value.password,
      };
    case "header": {
      const headers = stringRecord(value.headers);
      return headers ? { strategy: "header", headers } : undefined;
    }
    case "oauth2": {
      const authentication = getAuthenticationConfig(value.authentication);
      const state = getOAuthState(value.state);
      return {
        strategy: "oauth2",
        ...(authentication && { authentication }),
        ...(state && { state }),
      };
    }
    default:
      return undefined;
  }
}

function authCredentialFromServerConfig(
  serverConfig: Record<string, unknown>,
): MCPAuthCredential | undefined {
  return normalizeTaggedAuthCredential(serverConfig.auth);
}

function getRemoteSecretFields(entry: {
  auth?: MCPAuthCredential;
  headers?: Record<string, string>;
}): Partial<SdkMcpServerConfig> {
  const fields: Partial<SdkMcpServerConfig> = {};
  if (entry.auth && !hasRedactedMcpSecretLeaf(entry.auth)) {
    fields.auth = entry.auth;
  }
  if (entry.headers && Object.keys(entry.headers).length > 0) {
    fields.headers = entry.headers;
  }
  return fields;
}

function getRemoteServerFields(server: MCPServerConfig) {
  return {
    ...(server.name && { name: server.name }),
    url: server.url!,
    ...(server.headers && { headers: server.headers }),
    ...(server.auth && { auth: server.auth }),
  };
}

export function toMcpSseServer(server: MCPServerConfig): MCPSSEServer {
  return getRemoteServerFields(server);
}

export function toMcpShttpServer(server: MCPServerConfig): MCPSHTTPServer {
  return {
    ...getRemoteServerFields(server),
    ...(server.timeout !== undefined && { timeout: server.timeout }),
  };
}

export function toMcpStdioServer(server: MCPServerConfig): MCPStdioServer {
  return {
    name: server.name!,
    command: server.command!,
    ...(server.args && { args: server.args }),
    ...(server.env && { env: server.env }),
  };
}

function getAuthenticationConfig(
  value: unknown,
): MCPAuthenticationConfig | undefined {
  if (!value || typeof value !== "object") return undefined;
  const record = value as Record<string, unknown>;
  if (record.type !== "oauth") return undefined;
  const authentication: MCPAuthenticationConfig = { type: "oauth" };
  if (
    record.client_auth_method === "none" ||
    record.client_auth_method === "client_secret_post" ||
    record.client_auth_method === "client_secret_basic" ||
    record.client_auth_method === "private_key_jwt"
  ) {
    authentication.client_auth_method = record.client_auth_method;
  }
  if (typeof record.scopes === "string") {
    authentication.scopes = record.scopes;
  } else if (
    Array.isArray(record.scopes) &&
    record.scopes.every((scope) => typeof scope === "string")
  ) {
    authentication.scopes = record.scopes;
  }
  if (typeof record.client_name === "string") {
    authentication.client_name = record.client_name;
  }
  if (typeof record.client_metadata_url === "string") {
    authentication.client_metadata_url = record.client_metadata_url;
  }
  if (typeof record.client_id === "string") {
    authentication.client_id = record.client_id;
  }
  if (typeof record.client_secret === "string") {
    authentication.client_secret = record.client_secret;
  }
  if (
    record.additional_client_metadata &&
    typeof record.additional_client_metadata === "object" &&
    !Array.isArray(record.additional_client_metadata)
  ) {
    authentication.additional_client_metadata =
      record.additional_client_metadata as Record<string, MCPJsonValue>;
  }
  return authentication;
}

/**
 * Parse the SDK-native ``agent_settings.mcp_config`` value and convert it
 * to the frontend MCPConfig format used by UI components.
 */
export function parseMcpConfig(value: unknown): MCPConfig {
  const mcpConfig = getSdkMcpServerMap(value);
  if (!mcpConfig) {
    return { ...EMPTY_MCP_CONFIG };
  }

  const sseServers: (string | MCPSSEServer)[] = [];
  const stdioServers: MCPStdioServer[] = [];
  const shttpServers: (string | MCPSHTTPServer)[] = [];

  for (const [serverName, serverConfig] of Object.entries(mcpConfig)) {
    if (!isRecord(serverConfig)) continue;

    const url = serverConfig.url as string | undefined;

    if (url) {
      const transport = serverConfig.transport as string | undefined;
      const auth = authCredentialFromServerConfig(serverConfig);
      const headers = stringRecord(serverConfig.headers);

      if (transport === "sse") {
        const name = userGivenServerName(serverName, "sse");
        const server: MCPSSEServer = { url };
        if (name) server.name = name;
        if (auth) server.auth = auth;
        if (headers) server.headers = headers;
        sseServers.push(server);
      } else {
        const name = userGivenServerName(serverName, "shttp");
        const server: MCPSHTTPServer = { url };
        if (name) server.name = name;
        if (serverConfig.timeout != null) {
          server.timeout = serverConfig.timeout as number;
        }
        if (auth) server.auth = auth;
        if (headers) server.headers = headers;
        shttpServers.push(server);
      }
    } else {
      if (typeof serverConfig.command !== "string") continue;
      const stdioServer: MCPStdioServer = {
        name: serverName,
        command: serverConfig.command,
      };
      if (serverConfig.args) {
        stdioServer.args = serverConfig.args as string[];
      }
      if (serverConfig.env) {
        stdioServer.env = serverConfig.env as Record<string, string>;
      }
      stdioServers.push(stdioServer);
    }
  }

  return {
    sse_servers: sseServers,
    stdio_servers: stdioServers,
    shttp_servers: shttpServers,
  };
}

/**
 * Convert the frontend MCPConfig format back to the SDK-native server map
 * expected by agent_settings.mcp_config on the backend.
 *
 * Names are only suffixed (``_1``, ``_2``, …) when an earlier entry has
 * already claimed the bare base name. We intentionally do NOT use a single
 * monotonic counter across server types: that would, for example, rename a
 * stdio server "myname" to "myname_1" the moment any sse/shttp entry is
 * persisted ahead of it, and shift the suffix on every save as the count
 * of other server types changes. With per-base collision suffixing,
 * unrelated entries keep their human-meaningful names stable across edits.
 */
export function toSdkMcpConfig(config: MCPConfig): SdkMcpConfig | null {
  const mcpConfig: SdkMcpConfig = {};

  const reserve = (base: string): string => {
    const safeBase = toMcpServerName(base);
    if (!(safeBase in mcpConfig)) return safeBase;
    let i = 1;
    while (`${safeBase}_${i}` in mcpConfig) i += 1;
    return `${safeBase}_${i}`;
  };

  for (const entry of config.sse_servers) {
    const server: SdkMcpServerConfig = {};
    let name: string | undefined;
    if (typeof entry === "string") {
      server.url = entry;
    } else {
      name = entry.name;
      server.url = entry.url;
      Object.assign(server, getRemoteSecretFields(entry));
    }
    server.transport = "sse";
    mcpConfig[reserve(name || "sse")] = server;
  }

  for (const entry of config.shttp_servers) {
    const server: SdkMcpServerConfig = { transport: "http" };
    let name: string | undefined;
    if (typeof entry === "string") {
      server.url = entry;
    } else {
      name = entry.name;
      server.url = entry.url;
      Object.assign(server, getRemoteSecretFields(entry));
      if (entry.timeout != null) server.timeout = entry.timeout;
    }
    mcpConfig[reserve(name || "shttp")] = server;
  }

  for (const entry of config.stdio_servers) {
    const server: SdkMcpServerConfig = {
      command: entry.command,
    };
    if (entry.args) server.args = entry.args;
    if (entry.env) server.env = entry.env;
    mcpConfig[reserve(entry.name || "stdio")] = server;
  }

  return Object.keys(mcpConfig).length > 0 ? mcpConfig : null;
}
